
name: Unit Tests

on: [ push, pull_request, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      working-directory: ./ComposeDiet
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./ComposeDiet
      run: ./gradlew build
    - name: Run unit tests
      working-directory: ./ComposeDiet
      run: ./gradlew test
